apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-relay
  labels:
    app.kubernetes.io/name: cloudgrange-relay
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: cloudgrange-relay
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
