apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: cloudgrange-api
        static_configs:
          - targets: ['{{ .Release.Name }}-api:8080']
        metrics_path: /metrics
        scheme: http
      - job_name: cloudgrange-relay
        static_configs:
          - targets: ['{{ .Release.Name }}-relay:8443']
        metrics_path: /metrics
        scheme: http
