apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-keycloak
  labels:
    app.kubernetes.io/name: cloudgrange-keycloak
spec:
  selector:
    app.kubernetes.io/name: cloudgrange-keycloak
  ports:
    - { name: http, port: 8080, targetPort: http }
    - { name: management, port: 9000, targetPort: management }
