#!/usr/bin/env bash
# Copyright 2026 CloudGrange Contributors
# SPDX-License-Identifier: Apache-2.0
#
# install-relay.sh — Install the CloudGrange relay agent on a Linux Docker host.
# Standalone path: installs ONLY the relay container against a remote core API, using an
# enrollment token issued by the portal's Sites & Relays "Add a site" wizard (or by
# POST /api/v1/relays/enroll-token directly). Does not touch the rest of the on-prem stack.
#
# Usage:
#   bash install-relay.sh --api-url <URL> --api-key <KEY> --site-id <SITE-ID> [--name <NAME>] [--version <TAG>]
#
# One-liner (as generated by the portal's Sites & Relays "Add a site" wizard):
#   curl -sSL https://raw.githubusercontent.com/CloudGrange/cloudgrange-deployment-installer/main/scripts/install-relay.sh \
#     | bash -s -- --api-url <URL> --api-key <KEY> --site-id <SITE-ID>
#
# AB#9196: org/repo corrected from the placeholder "cloudgrange-cloud/cloudgrange-installer"
# (neither exists) to this repo's real remote, github.com/CloudGrange/cloudgrange-deployment-installer.

set -euo pipefail

CONTAINER_NAME="cloudgrange-relay"
VOLUME_NAME="cloudgrange-relay-identity"
IMAGE_BASE="ghcr.io/cloudgrange/cloudgrange-relay"
# AB#9196: relay releases live in cloudgrange-runtime-relay (the relay's own repo), not a
# nonexistent "cloudgrange-relay" repo, and the org is "CloudGrange" not "cloudgrange-cloud".
RELEASES_URL="https://api.github.com/repos/CloudGrange/cloudgrange-runtime-relay/releases"
HEALTH_TIMEOUT=30

# ----------------------------------------------------------------------------
# Argument parsing
# ----------------------------------------------------------------------------
API_URL=""
API_KEY=""
SITE_ID=""
VERSION=""

usage() {
    echo "Usage: $0 --api-url <URL> --api-key <KEY> --site-id <SITE-ID> [--version <TAG>]"
    exit 1
}

RELAY_NAME=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --api-url)   API_URL="$2";  shift 2 ;;
        --api-key)   API_KEY="$2";  shift 2 ;;
        --site-id)   SITE_ID="$2";  shift 2 ;;
        --name)      RELAY_NAME="$2"; shift 2 ;;
        --version)   VERSION="$2";  shift 2 ;;
        -h|--help)   usage ;;
        *) echo "Unknown argument: $1"; usage ;;
    esac
done

if [[ -z "$API_URL" || -z "$API_KEY" || -z "$SITE_ID" ]]; then
    echo "Error: --api-url, --api-key, and --site-id are all required."
    usage
fi

# ----------------------------------------------------------------------------
# Docker check
# ----------------------------------------------------------------------------
if ! command -v docker &>/dev/null; then
    echo ""
    echo "Error: Docker is not installed or not on PATH."
    echo ""
    echo "Install Docker Engine on Debian/Ubuntu:"
    echo "  curl -fsSL https://get.docker.com | sh"
    echo ""
    echo "Or follow the official guide:"
    echo "  https://docs.docker.com/engine/install/"
    echo ""
    exit 1
fi

if ! docker info &>/dev/null; then
    echo ""
    echo "Error: Docker daemon is not running, or you do not have permission to access it."
    echo ""
    echo "Start the daemon:  sudo systemctl start docker"
    echo "Add your user:     sudo usermod -aG docker \$USER  (then log out and back in)"
    echo ""
    exit 1
fi

# ----------------------------------------------------------------------------
# Resolve version
# ----------------------------------------------------------------------------
if [[ -z "$VERSION" ]]; then
    echo "Resolving latest relay version..."
    VERSION=$(curl -sSL "${RELEASES_URL}/latest" | grep '"tag_name"' | head -1 | sed 's/.*"tag_name": *"\([^"]*\)".*/\1/')
    if [[ -z "$VERSION" ]]; then
        echo "Warning: Could not resolve latest version from GitHub releases. Falling back to 'latest' tag."
        VERSION="latest"
    else
        echo "Latest version: ${VERSION}"
    fi
fi

IMAGE="${IMAGE_BASE}:${VERSION}"

# ----------------------------------------------------------------------------
# Pull image
# ----------------------------------------------------------------------------
echo "Pulling ${IMAGE} ..."
docker pull "${IMAGE}"

# ----------------------------------------------------------------------------
# Verify image digest against GitHub releases manifest (best-effort)
# ----------------------------------------------------------------------------
EXPECTED_DIGEST=""
if [[ "$VERSION" != "latest" ]]; then
    # AB#9196: org/repo corrected (see RELEASES_URL above); this manifest asset is not
    # currently published by cloudgrange-runtime-relay's release workflow, so this step
    # stays best-effort ("skipping verification" below) until that changes.
    MANIFEST_URL="https://github.com/CloudGrange/cloudgrange-runtime-relay/releases/download/${VERSION}/cloudgrange-relay.sha256"
    echo "Verifying image digest from ${MANIFEST_URL} ..."
    MANIFEST=$(curl -sSL --fail "${MANIFEST_URL}" 2>/dev/null || true)
    if [[ -n "$MANIFEST" ]]; then
        EXPECTED_DIGEST=$(echo "$MANIFEST" | grep "cloudgrange-relay" | awk '{print $1}' | head -1)
    fi
fi

if [[ -n "$EXPECTED_DIGEST" ]]; then
    ACTUAL_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' "${IMAGE}" 2>/dev/null | cut -d'@' -f2 || true)
    if [[ -z "$ACTUAL_DIGEST" ]]; then
        echo "Warning: Could not retrieve local image digest — skipping verification."
    elif [[ "$ACTUAL_DIGEST" == *"$EXPECTED_DIGEST"* ]]; then
        echo "Digest verified: ${ACTUAL_DIGEST}"
    else
        echo "Error: Image digest mismatch."
        echo "  Expected (from manifest): ${EXPECTED_DIGEST}"
        echo "  Actual:                   ${ACTUAL_DIGEST}"
        echo "Do not run untrusted images. Aborting."
        exit 1
    fi
else
    echo "Digest manifest not available for this version — skipping verification."
fi

# ----------------------------------------------------------------------------
# Remove existing container if present
# ----------------------------------------------------------------------------
if docker inspect "${CONTAINER_NAME}" &>/dev/null; then
    echo "Stopping and removing existing container '${CONTAINER_NAME}' ..."
    docker rm -f "${CONTAINER_NAME}"
fi

# ----------------------------------------------------------------------------
# Run the relay container
# ----------------------------------------------------------------------------
# AB#9196: env vars corrected to match what the relay binary actually reads
# (cloudgrange-runtime-relay/src/CloudGrange.Relay/Program.cs). The previous
# RELAY_API_URL/RELAY_API_KEY names are not read by the relay at all — RELAY_PAAS_URL is
# required and throws on startup if unset, so every standalone install using the old names
# would fail immediately. A named volume persists the relay's enrolled identity (private key +
# relayId under RELAY_IDENTITY_DIR) across container recreates, so re-running this script (or a
# restart) does not force a doomed re-enrollment with an already-consumed token.
echo "Ensuring identity volume '${VOLUME_NAME}' exists ..."
docker volume create "${VOLUME_NAME}" >/dev/null

echo "Starting relay container ..."
docker run -d \
    --name "${CONTAINER_NAME}" \
    --restart unless-stopped \
    -e RELAY_PAAS_URL="${API_URL}" \
    -e RELAY_ENROLLMENT_TOKEN="${API_KEY}" \
    -e RELAY_SITE_ID="${SITE_ID}" \
    ${RELAY_NAME:+-e "RELAY_DISPLAY_NAME=${RELAY_NAME}"} \
    -v "${VOLUME_NAME}:/var/lib/cloudgrange-relay/identity" \
    "${IMAGE}"

# ----------------------------------------------------------------------------
# Wait for healthy
# ----------------------------------------------------------------------------
echo "Waiting up to ${HEALTH_TIMEOUT}s for container to become healthy ..."
ELAPSED=0
HEALTHY=false
while [[ $ELAPSED -lt $HEALTH_TIMEOUT ]]; do
    STATUS=$(docker inspect --format='{{.State.Status}}' "${CONTAINER_NAME}" 2>/dev/null || echo "unknown")
    HEALTH=$(docker inspect --format='{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}' "${CONTAINER_NAME}" 2>/dev/null || echo "unknown")

    if [[ "$STATUS" == "running" && ("$HEALTH" == "healthy" || "$HEALTH" == "none") ]]; then
        HEALTHY=true
        break
    fi

    if [[ "$STATUS" == "exited" || "$STATUS" == "dead" ]]; then
        echo ""
        echo "Error: Container exited unexpectedly. Logs:"
        docker logs "${CONTAINER_NAME}" 2>&1 | tail -20
        exit 1
    fi

    sleep 2
    ELAPSED=$((ELAPSED + 2))
done

if [[ "$HEALTHY" != "true" ]]; then
    echo ""
    echo "Warning: Container did not report healthy within ${HEALTH_TIMEOUT}s."
    echo "Container status: $(docker inspect --format='{{.State.Status}}' "${CONTAINER_NAME}" 2>/dev/null)"
    echo ""
    echo "Check logs with:  docker logs ${CONTAINER_NAME}"
    exit 1
fi

# ----------------------------------------------------------------------------
# Done
# ----------------------------------------------------------------------------
echo ""
echo "Relay agent connected. Check the CloudGrange portal to confirm Active status."
echo ""
echo "Useful commands:"
echo "  View logs:   docker logs -f ${CONTAINER_NAME}"
echo "  Stop relay:  docker stop ${CONTAINER_NAME}"
echo "  Uninstall:   curl -sSL https://raw.githubusercontent.com/CloudGrange/cloudgrange-deployment-installer/main/scripts/uninstall-relay.sh | bash"
